version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Basyolog
      - public-data:/Basyolog/public
      - tmp-data:/Basyolog/tmp
      - log-data:/Basyolog/log

  app:
    build:
      context: containers/nginx
    volumes:
      - public-data:/Basyolog/public
      - tmp-data:/Basyolog/tmp
    ports:
      - 80:80

volumes:
  public-data:
  tmp-data:
  log-data: