version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: Basyolog_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Basyolog
      - public-data:/Basyolog/public
      - tmp-data:/Basyolog/tmp
      - log-data:/Basyolog/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/Basyolog/public
      - tmp-data:/Basyolog/tmp
    ports:
      - 80:80

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: